test old ver

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -66,33 +66,25 @@ BUILDPACK_BRANCH=${BUILDPACK_BRANCH:-master}
 if [[ "$BUILDPACK_BRANCH" != v* && "$BUILDPACK_BRANCH" != "master" ]]; then
     S3_URL="develop"
 fi
-#S3_URL="https://lang-php.s3.amazonaws.com/dist-${STACK}-${S3_URL:-"master"}"
-S3_URL="https://s3-ap-southeast-1.amazonaws.com/tungns-heroku/buildpack"
+# S3_URL="https://lang-php.s3.amazonaws.com/dist-${STACK}-${S3_URL:-"master"}"
 S3_URL="https://s3.amazonaws.com/tiki-heroku-buildpacks/nginx-php-phalcon"
+
 RTVS_URL="https://php-runtime-version-selector.herokuapp.com"
 
 cd $BUILD_DIR
 
-if [[ -n ${COMPOSER:-} ]]; then
-    status "Using '$COMPOSER' (from "'$COMPOSER env var) for installation.'
+if [[ -s "composer.json" ]]; then
+    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
 else
-    export COMPOSER="composer.json"
-fi
-COMPOSER_LOCK=$(basename "$COMPOSER" ".json")".lock" # replace .json with .lock if it exists, append .lock otherwise
-
-
-if [[ -s "$COMPOSER" ]]; then
-    cat "$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
-else
-    if [[ ! -f "$COMPOSER" ]]; then
-        warning "No '$COMPOSER' found.
-Using 'index.php' to declare PHP applications is considered legacy
-functionality and may lead to unexpected behavior."
+    if [[ ! -f "composer.json" ]]; then
+        warning 'No composer.json found.
+Using index.php to declare PHP applications is considered legacy
+functionality and may lead to unexpected behavior.'
     else
-        notice "Your '$COMPOSER' is completely empty.
-Please change its contents to at least '{}' so it is valid JSON."
+        notice 'Your composer.json is completely empty.
+Please change its contents to at least "{}" so it is valid JSON.'
     fi
-    echo "{}" > $COMPOSER
+    echo "{}" > composer.json
 fi
 
 mkdir -p .heroku/php
@@ -109,62 +101,42 @@ else
 fi
 engine="php"
 engine_r="php -r"
-if [[ -f "$COMPOSER" ]]; then
-    if [[ ! -f "$COMPOSER_LOCK" ]]; then
-        cat composer.json | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your '$COMPOSER' lists dependencies inside 'require',
-but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
-re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
-repository. For more information, please refer to the docs at
-https://devcenter.heroku.com/articles/php-support#activation"
-    fi
+if [[ -f "composer.json" ]]; then
+#    if [[ ! -f "composer.lock" ]]; then
+#        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
+#was found, check it into your repository alongside composer.json!"
+#    fi
     
     solver_payload=$(echo -n "$runtimes" | python -c '
 import sys, json
 ret = {}
 ret["packages"] = sys.stdin.read().splitlines()
+c_json = dict(json.load(open("composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
+ret["json"] = {k: c_json.get(k, None) for k in ["minimum-stability", "prefer-stable"]}
+ret["json"]["platform"] = {k: dict(c_json.get("require", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 try:
-    c_lock = json.load(open(sys.argv[1]))
+    c_lock = json.load(open("composer.lock"))
     ret["lock"] = {k: c_lock.get(k, None) for k in ["minimum-stability", "prefer-stable", "stability-flags"]}
     ret["lock"]["platform"] = {k: dict(c_lock.get("platform", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 except IOError:
     ret["lock"] = None
 print json.dumps(ret)
-' "$COMPOSER_LOCK" 2> /dev/null) || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
+' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
 Run 'composer update' to have it re-generated by Composer."
-
-    # warn if minimum-stability is set to non-stable (regardless of whether prefer-stable is used)
-    if echo -n "$solver_payload" | python -c 'import sys, json; p = json.load(sys.stdin); sys.exit(p["lock"] == None or p["lock"]["minimum-stability"] == "stable");' 2> /dev/null; then
-        warning "Your 'composer.json' contains a non-'stable' setting
-for 'minimum-stability'. This may cause the installation of
-unstable versions of runtimes and extensions during this deploy.
-It is recommended that you always use stability flags instead,
-even if you have 'prefer-stable' enabled. For more information,
-see https://getcomposer.org/doc/01-basic-usage.md#stability"
-    fi
-    
     solver_result=$(echo -n "$solver_payload" | curl --silent --location --fail -H'Content-Type: application/json' -H"X-Build-Request-Id: ${REQUEST_ID:-}" -d @- "${RTVS_URL}/resolve?default_runtime=php") || error "Failed to resolve runtime requirements.
 If the issue persists, please contact support."
     while IFS="|" read runtime_name runtime_source runtime_constraint runtime_result; do
-        # make sure we use the correct names for "composer.json" and "composer.lock"
-        case "$runtime_source" in
-            "composer.json")
-                runtime_source="$COMPOSER"
-                ;;
-            "composer.lock")
-                runtime_source="$COMPOSER_LOCK"
-                ;;
-        esac
         if [[ $runtime_result ]]; then
             if [[ $runtime_source == "default" ]]; then
-                status "No runtime required in '$COMPOSER', defaulting to ${runtime_name^^} $runtime_result."
+                status "No runtime required in composer.json, defaulting to ${runtime_name^^} $runtime_result."
             else
-                status "Resolved '$runtime_source' requirement for ${runtime_name^^} to version ${runtime_result}."
+                status "Resolved $runtime_source requirement for ${runtime_name^^} to version ${runtime_result}."
                 if [[ "$runtime_constraint" == "$runtime_result" || "$runtime_constraint" == "=$runtime_result" ]]; then
                     recommended_selector="~$runtime_result"
                     if [[ $runtime_name == "hhvm" ]]; then
                         recommended_selector="${recommended_selector%.*}" # strip "3.2.0" to just "3.2"; HHVM has different versioning
                     fi
-                    warning "Your '$COMPOSER' requirement for runtime '$runtime_name'
+                    warning "Your composer.json requirement for runtime '$runtime_name'
 specifies an exact-match constraint of '$runtime_constraint'.
 This means you will not automatically get more recent compatible
 versions of ${runtime_name^^} on push once they are available. As any such
@@ -185,9 +157,17 @@ will be removed soon. Please upgrade to cedar-14 to continue to
 use HHVM and get access to new releases. For more information,
 see https://devcenter.heroku.com/articles/cedar-14-migration"
                 fi
+                if [[ -f "composer.lock" ]] && python -c 'import sys, json; print sys.exit(any(key.count("hhvm") for key in json.load(open("composer.lock")).get("platform", {})))' 2> /dev/null; then
+                    warning_inline "Support for requiring HHVM in 'composer.json' but not in
+'composer.lock' is deprecated and will be removed soon. Please
+update 'composer.lock' to contain the requirement. If you do not
+have HHVM installed, you can re-generate the lock file using the
+'composer update --ignore-platform-reqs' command; the same switch
+may be used with 'composer install' under the same circumstances."
+                fi
             fi
         else
-            error "Could not resolve '$runtime_source' requirement for ${runtime_name^^} $runtime_constraint,
+            error "Could not resolve $runtime_source requirement for ${runtime_name^^} $runtime_constraint,
 please adjust the selector. The following runtimes are available:
 $(echo $runtimes | fold -s -w 65)"
         fi
@@ -249,6 +229,16 @@ cp $BP_DIR/conf/nginx/nginx.conf.default $BUILD_DIR/.heroku/php/etc/nginx/nginx.
 mkdir -p $BUILD_DIR/.heroku/php/.versions/nginx
 echo $NGINX_VERSION > $BUILD_DIR/.heroku/php/.versions/nginx/nginx
 
+REDIS_VERSION="3.0.3"
+REDIS_DIST_URL="$S3_URL/redis.tar.gz"
+echo "- Redis $REDIS_VERSION" | indent
+mkdir -p .heroku/redis
+curl --silent --location "$REDIS_DIST_URL" | tar xz -C $BUILD_DIR/.heroku/redis
+# store Apache version in the slug for possible later evaluation
+mkdir -p $BUILD_DIR/.heroku/php/.versions/redis
+echo $REDIS_VERSION > $BUILD_DIR/.heroku/php/.versions/redis/redis
+
+
 # handle extensions for PHP
 if [[ "${PHP_VERSION}" ]]; then
     status "Installing PHP extensions..."
@@ -259,12 +249,12 @@ if [[ "${PHP_VERSION}" ]]; then
     }
     
     exts=()
-    if [[ -f "$COMPOSER_LOCK" ]]; then
-        exts=($(cat "$COMPOSER_LOCK" | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
-        ext_source="$COMPOSER_LOCK"
+    if [[ -f "composer.lock" ]]; then
+        exts=($(cat composer.lock | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
+        ext_source="composer.lock"
     else
-        exts=($(cat "$COMPOSER" | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
-        ext_source="$COMPOSER"
+        exts=($(cat composer.json | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
+        ext_source="composer.json"
     fi
     for ext in "${!exts[@]}"; do # loop over keys in case the array is empty or else it'll error out
         install_ext "${exts[$ext]}" $ext_source
@@ -281,6 +271,7 @@ if [[ "${PHP_VERSION}" ]]; then
         exts+=("zend-opcache")
     fi
 fi
+
 
 status "Installing dependencies..."
 
@@ -309,7 +300,7 @@ composer --version 2> /dev/null | tail -n 1 | indent
 if [[ -e "$(composer config vendor-dir 2> /dev/null | tail -n 1)" ]]; then # tail, as composer echos outdated version warnings to STDOUT
     warning "Your Composer vendor dir is part of your Git repository.
 That directory should not be under version control; only your
-'$COMPOSER' and '$COMPOSER_LOCK' files should be added, which
+'composer.json' and 'composer.lock' files should be added, which
 will let Composer handle installation of dependencies on deploy.
 To suppress this notice, first remove the folder from your index
 by running 'git rm --cached $(composer config vendor-dir 2> /dev/null | tail -n 1)/'.
@@ -341,12 +332,12 @@ fi
 unset COMPOSER_GITHUB_OAUTH_TOKEN
 
 # install dependencies unless composer.json is completely empty (in which case it'd talk to packagist.org which may be slow and is unnecessary)
-cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
+cat composer.json | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
 
-composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
+composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-if cat "$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+if cat composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
     status "Running 'composer compile'..."
     composer run-script --no-dev --no-interaction compile 2>&1 | indent
 fi
@@ -410,6 +401,6 @@ install_blackfire_agent
 
 if [[ ! -f "Procfile" ]]; then
     bindir=$(composer config bin-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
-    echo "web: $bindir/heroku-$engine-apache2" > Procfile
-    notice_inline "No Procfile, using 'web: $bindir/heroku-$engine-apache2'."
+    echo "web: $bindir/heroku-$engine-nginx" > Procfile
+    notice_inline "No Procfile, using 'web: $bindir/heroku-$engine-nginx'."
 fi
